/*
  # Fix Agents and Admins Tables for User Creation

  1. Changes to Tables
    - `agents`
      - Add auto-increment to id column
    
    - `admins`
      - Add role column (alias for admin_role to maintain compatibility)
  
  2. Notes
    - Agents table id needs to be a serial/auto-increment
    - Admins table uses admin_role but we need role for compatibility
*/

ALTER TABLE agents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'admins' AND column_name = 'role'
  ) THEN
    ALTER TABLE admins ADD COLUMN role text;
    UPDATE admins SET role = admin_role WHERE role IS NULL;
    ALTER TABLE admins ALTER COLUMN role SET NOT NULL;
    ALTER TABLE admins ADD CONSTRAINT admins_role_check CHECK (role = ANY (ARRAY['overview'::text, 'sales'::text, 'agents'::text, 'tech'::text]));
  END IF;
END $$;