/*
  # Update payments table to use auto-incrementing ID

  1. Changes
    - Convert payments.id to use SERIAL (auto-incrementing)
    - Create sequence for automatic ID generation
    
  2. Important Notes
    - This ensures no ID conflicts when inserting payments
    - IDs will be automatically generated by the database
*/

DO $$
BEGIN
  -- Create a sequence if it doesn't exist
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'payments_id_seq') THEN
    CREATE SEQUENCE payments_id_seq;
    
    -- Set the sequence to start from the max existing ID + 1
    PERFORM setval('payments_id_seq', COALESCE((SELECT MAX(id) FROM payments), 0) + 1, false);
    
    -- Set the default value for the id column to use the sequence
    ALTER TABLE payments ALTER COLUMN id SET DEFAULT nextval('payments_id_seq');
    
    -- Set the sequence ownership
    ALTER SEQUENCE payments_id_seq OWNED BY payments.id;
  END IF;
END $$;